<!DOCTYPE html>
<html lang="en" style="font-size: 16px;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="/fontawesome/css/all.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
</head>
<body class="bg-[url('/IT_Academy/Sprint3/Developers/web/images/fondo.png')] bg-cover bg-center h-screen flex items-center justify-center relative" style="font-size: 16px; font-family: 'Roboto', sans-serif;"> <!-- fondo -->
<?php if ($this->taskChosen) { ?>
    <section class="dark:bg-gray-900">
      <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16 relative">
          <a href="./" class="top-left-button" style="top: 10px; left: 20px;">
              <i class="fa-solid fa-arrow-left" style="font-size: 14px;"></i><span class="small-text" style="margin-left: 5px;">Ver listas</span>
          </a>
          <h2 class="mb-6 mt-4 text-xl font-bold text-gray-900 dark:text-white"><?php echo $this->taskChosen['nombre']; ?></h2> <!-- Nombre de la tarea -->
          <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
              <div class="relative max-w-sm">
                  <label for="vencimiento" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Vencimiento</label>
                  <input type="text" name="vencimiento" id="vencimiento" class="bg-gray-50 text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" value="<?php echo $this->taskChosen['vencimiento']; ?>" readonly style="outline: none;">
              </div>
              <div class="w-full">
                  <label for="estado" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Estado</label>
                  <input name="estado" id="estado" class="bg-gray-50 text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" value="<?php echo $this->taskChosen['estado']; ?>" readonly style="outline: none;">
              </div>
              <div class="sm:col-span-2">
                  <label for="descripcion" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Descripción</label>
                  <textarea name="descripcion" id="descripcion" rows="8" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" readonly style="outline: none;"><?php echo $this->taskChosen['descripcion']; ?></textarea>
              </div>
          </div>
      </div>
    </section>
<?php } ?>
</body>
</html>

