<!DOCTYPE html>
<html lang="en" style="font-size: 16px;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="/fontawesome/css/all.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
</head>
<body class="bg-[url('images/fondo.png')] bg-cover bg-center h-screen flex items-center justify-center relative">
<?php if ($this->taskChosen) { ?>
    <section class="dark:bg-gray-900">
        <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16 relative">
            <a href="./" class="top-left-button" style="top: 10px; left: 20px;">
                <i class="fa-solid fa-arrow-left" style="position: absolute; top: 15px; font-size: 14px;"></i><span class="small-text text-shadow" style="position: absolute; top: 10px; margin-left: 5px; left: 30px;">Volver a las listas</span>
            </a>
            <h2 class="mb-6 mt-4 text-xl font-bold text-gray-900 dark:text-white">
                <?php echo $this->taskChosen["nombre"]; ?>
            </h2>
            <form action="update" method="POST" onsubmit="return confirm('¿Estás seguro de que deseas cambiar esta tarea?');">
                <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                    <!-- calendario -->   
                   <div class="relative max-w-sm"> 
                     <label for="vencimiento" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Vencimiento</label>
                      <div class="absolute inset-y-12 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                       </svg>
                      </div>
                    <input name="vencimiento" id="vencimiento" datepicker datepicker-orientation="bottom right" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder= <?php echo $this->taskChosen["vencimiento"]; ?> required="">
                   </div>
                   <!-- estado --> 
                    <div class="w-full">
                        <label for="estado" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Estado</label>
                        <input name="estado" id="estado" class="bg-gray-50 text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" value="<?php echo $this->taskChosen["estado"]; ?>" style="outline: none;" required="">
                    </div>
                    <div class="sm:col-span-2">
                        <label for="descripcion" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Descripción</label>
                        <textarea name="descripcion" id="descripcion" rows="8" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" style="outline: none;" ><?php echo $this->taskChosen["descripcion"]; ?></textarea>
                    </div>
                    <input type="hidden" name="nombre" value="<?php echo $this->taskChosen["nombre"]; ?>">
                </div>
                <button type="submit" class="text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mt-4 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-red-500">Guardar</button>
            </form>
        </div>
    </section>
<?php } ?>
</body>
</html>