<!DOCTYPE html>
<html lang="en" style="font-size: 16px;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="/fontawesome/css/all.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
</head>
<body class="bg-[url('images/fondo.png')] bg-cover bg-center h-screen flex items-center justify-center relative">
<?php if ($this->taskChosen) { ?>
    <section class="dark:bg-gray-900">
        <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16 relative">
            <a href="./" class="top-left-button" style="top: 10px; left: 20px;">
                <i class="fa-solid fa-arrow-left" style="position: absolute; top: 15px; font-size: 14px;"></i><span class="small-text text-shadow" style="position: absolute; top: 10px; margin-left: 5px; left: 30px;">Volver a las listas</span>
            </a>
            <div class="w-full sm:col-span-2">
                <form action="./" method="POST">
                    <label for="nombre" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre</label>
                    <input type="text" name="nombre" id="nombre" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 focus:border-2 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:focus:border-2" value="<?php echo $this->taskChosen["nombre"]; ?>" style="outline: none;">
                </div>
                <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                    <div class="relative max-w-sm">
                        <label for="vencimiento" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Vencimiento</label>
                        <input type="text" name="vencimiento" id="vencimiento" class="bg-gray-50 text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" value="<?php echo $this->taskChosen["vencimiento"]; ?>" style="outline: none;">
                    </div>
                    <div class="w-full">
                        <label for="estado" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Estado</label>
                        <input name="estado" id="estado" class="bg-gray-50 text-gray-900 text-sm rounded-lg block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" value="<?php echo $this->taskChosen["estado"]; ?>" style="outline: none;">
                    </div>
                    <div class="sm:col-span-2">
                        <label for="descripcion" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Descripción</label>
                        <textarea name="descripcion" id="descripcion" rows="8" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white" style="outline: none;"><?php echo $this->taskChosen["descripcion"]; ?></textarea>
                    </div>
                </div>
                <!-- Icono de basurero -->
                <button type="submit" name="update_task" class="text-white bg-red-400 hover:bg-red-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mt-4 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-red-500">Guardar</button>
            </form>  
        </div>
    </section>
<?php } ?>
</body>
</html>
